#!/usr/bin/env php
<?php

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

umask(0000);

set_time_limit(0);

$loader = require __DIR__ . '/autoload.php';
require_once __DIR__ . '/AppKernel.php';

$input = new ArgvInput();

$dotenv = new \Dotenv\Dotenv(__DIR__ . '/../');
$dotenv->load();

$env = $_SERVER['SYMFONY_ENV'];
$debug = $_SERVER['SYMFONY_DEBUG'];

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
